version: '3.9'

services:
  web:
    build: .
    container_name: faq_django
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DEBUG=True
    volumes:
      - .:/app

  redis:
    image: "redis:alpine"
    container_name: faq_redis
    restart: always
    ports:
      - "6379:6379"
